export default {
    defaultData: {
        exp: 0,
        coin: 10,
        nivel: 0,
        role: 'Novato'
    },
    cantidad: {
        mineria: 1500, // XP por minería
        tiempoMinera: 2 * 60 * 60 * 1000, // 2 horas
        robar: 1000, // XP por robar
        tiempoRobar: 2 * 60 * 60 * 1000, // 2 horas
        claimFree: 3000, // XP gratis
        claimPrem: 5000, // XP premium
        tiempoClaim: 24 * 60 * 60 * 1000 // 24 horas
    },
    precios: {
        coin: 100,
        nivel: 500
    },
    roles: [
        { name: 'Novato', nivel: 1 },
        { name: 'Guerrero de Entrenamiento', nivel: 2 },
        { name: 'Explorador Aprendiz', nivel: 3 },
        { name: 'Defensor del Reino', nivel: 4 },
        { name: 'Cazador de Monstruos', nivel: 5 },
        { name: 'Caballero Novato', nivel: 6 },
        { name: 'Guerrero Experimentado', nivel: 7 },
        { name: 'Maestro de Armas', nivel: 8 },
        { name: 'Héroe Legendario', nivel: 9 },
        { name: 'Conquistador', nivel: 10 },
        { name: 'Señor de los Dragones', nivel: 11 },
        { name: 'Dios de la Batalla', nivel: 12 },
        { name: 'Gran Hechicero', nivel: 13 },
        { name: 'Guardián del Multiverso', nivel: 14 },
        { name: 'Emperador de los Héroes', nivel: 15 },
        { name: 'Líder de la Resistencia', nivel: 16 },
        { name: 'Supremo Maestro del PVP', nivel: 17 },
        { name: 'Conde de la Estrategia', nivel: 18 },
        { name: 'Ser Supremo del Juego', nivel: 19 },
        { name: 'Avatar de la Imaginación', nivel: 20 },
        { name: 'Rey de los Videojuegos', nivel: 21 },
        { name: 'Dios de la Diversión', nivel: 22 },
        { name: 'Maestro de la Inventiva', nivel: 23 },
        { name: 'Guía de Titanes', nivel: 24 },
        { name: 'Vidente de la Sabiduría', nivel: 25 },
        { name: 'Archimago del Juego', nivel: 26 },
        { name: 'Valiente del Futuro', nivel: 27 },
        { name: 'Laurentino Heroico', nivel: 28 },
        { name: 'Guardán de Secretos', nivel: 29 },
        { name: 'Dios de la Sabiduría', nivel: 30 },
        { name: 'Súper Gran Maestro', nivel: 31 },
        { name: 'Místico de las Adivinaciones', nivel: 32 },
        { name: ' Avatar de todos los Saber', nivel: 33 },
        { name: 'Líder Épico de las Leyendas', nivel: 34 },
        { name: 'Dioses Antiguos del Multiverso', nivel: 35 },
        { name: 'Señor del Caos', nivel: 36 },
        { name: 'Creador de Mundos', nivel: 37 },
        { name: 'Héroe de la Infinidad', nivel: 38 },
        { name: 'Dios de la Risas Eternas', nivel: 39 },
        { name: 'El Último Guardián', nivel: 40 },
        { name: 'Soberano de la Aventura', nivel: 41 },
        { name: 'Rey de los Campeones', nivel: 42 },
        { name: 'Dios de la Estrategia Épica', nivel: 43 },
        { name: 'Guardián de la Realidad Virtual', nivel: 44 },
        { name: 'Cazador de Conquistas', nivel: 45 },
        { name: 'Dios del Multiverso Incógnito', nivel: 46 },
        { name: 'Avatar de lo Desconocido', nivel: 47 },
        { name: 'Maestro del Tiempodivertido', nivel: 48 },
        { name: 'Líder de la Actualidad', nivel: 49 },
        { name: 'Guardian del Modo Sorpresa', nivel: 50 },
        { name: 'Emperador de los Videojuegos', nivel: 51 },
        { name: 'Dios de la Innovación', nivel: 52 },
        { name: 'Señor de las Conquistas', nivel: 53 },
        { name: 'Creador de Realidades Paralelas', nivel: 54 },
        { name: 'Elegido del Multiverso', nivel: 55 },
        { name: 'Maestro de la Realidad', nivel: 56 },
        { name: 'Dios de la Diversión y el Caos', nivel: 57 },
        { name: 'El Gran Archimago', nivel: 58 },
        { name: 'Maestro de la Transformación', nivel: 59 },
        { name: 'Dios de las Leyendas', nivel: 60 },
        { name: 'Rey de los Gráficos Épicos', nivel: 61 },
        { name: 'Iluminado por la Sabiduría', nivel: 62 },
        { name: 'Dios del Mando', nivel: 63 },
        { name: 'Creador de Horizonte Infinito', nivel: 64 },
        { name: 'Comandante Supremo', nivel: 65 },
        { name: 'Dios de la Experiencia', nivel: 66 },
        { name: 'Líder del Desafío', nivel: 67 },
        { name: 'Profeta de la Innovación', nivel: 68 },
        { name: 'Guardian de la Imaginación', nivel: 69 },
        { name: 'Avatar de la Diversión Infinita', nivel: 70 },
        { name: 'Gran Visionario', nivel: 71 },
        { name: 'Dios de la Fantasía', nivel: 72 },
        { name: 'Héroe Multidimensional', nivel: 73 },
        { name: 'Supremo de los Códigos', nivel: 74 },
        { name: 'Viajerode Realidades', nivel: 75 },
        { name: 'Guardían del Conocimiento', nivel: 76 },
        { name: 'Legado de los Héroes', nivel: 77 },
        { name: 'Explorador de Nuevas Dimensiones', nivel: 78 },
        { name: 'Señor de las Estrategias Épicas', nivel: 79 },
        { name: 'Dios de la Narrativa', nivel: 80 },
        { name: 'El Último Maestro', nivel: 81 },
        { name: 'Diseñador de Universos', nivel: 82 },
        { name: 'Rey de la Narración', nivel: 83 },
        { name: 'Guardian de la Inspiración', nivel: 84 },
        { name: 'Dios de la Creatividad', nivel: 85 },
        { name: 'Conquistador del Imposible', nivel: 86 },
        { name: 'Estrella Fugaz', nivel: 87 },
        { name: 'Comandante de la Élite', nivel: 88 },
        { name: 'Soberano de la Frikimanía', nivel: 89 },
        { name: 'Dios de la Diversión Intergaláctica', nivel: 90 },
        { name: 'El Maestro del Myths', nivel: 91 },
        { name: 'Guardian de las Realidades Alternativas', nivel: 92 },
        { name: 'Dioses de la Infinidad', nivel: 93 },
        { name: 'El Último Genio', nivel: 94 },
        { name: 'Monarca del Tesoro', nivel: 95 },
        { name: 'Dios de la Aventura', nivel: 96 },
        { name: 'Guardián de las Galaxias', nivel: 97 },
        { name: 'Creador de la Eternidad', nivel: 98 },
        { name: 'El Más Poderoso', nivel: 99 },
        { name: 'El Divino Maestro de Juegos', nivel: 100 }
    ]
}